# Generated by Django 5.1.7 on 2025-05-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
