# Generated by Django 5.2 on 2025-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artworkcomment_artworklike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='custom_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='frame',
            field=models.CharField(choices=[('none', 'No Frame'), ('wood', 'Wood Frame (+৳300)'), ('metal', 'Metal Frame (+৳350)'), ('acrylic', 'Acrylic Frame (+৳250)')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, choices=[('A4', 'A4 (8.3×11.7 in)'), ('A3', 'A3 (11.7×16.5 in)'), ('A2', 'A2 (16.5×23.4 in)'), ('A1', 'A1 (23.4×33.1 in)'), ('18x24', '18×24 in'), ('24x36', '24×36 in')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='art_type',
            field=models.CharField(choices=[('traditional', 'Traditional Art'), ('photography', 'Photography'), ('poster', 'Poster'), ('exclusive_paintings', 'Exclusive Paintings'), ('print', 'Print'), ('digital', 'Digital Art'), ('illustration', 'Illustration'), ('3d', '3D Art / Sculpting'), ('handmade_crafts', 'Handmade Crafts')], max_length=30),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('landscape', 'Landscape'), ('portrait', 'Portrait'), ('fantasy', 'Fantasy'), ('food', 'Food'), ('nature', 'Nature'), ('cityscape', 'Cityscape / Urban'), ('animals', 'Animals / Wildlife'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('mythology', 'Mythology'), ('aesthetic', 'Aesthetic / Minimalism'), ('dark_art', 'Dark Art'), ('vintage', 'Vintage / Retro'), ('surreal', 'Surreal / Dreamy')], max_length=50),
        ),
        migrations.AddField(
            model_name='artwork',
            name='categories',
            field=models.ManyToManyField(to='artworks.category'),
        ),
    ]
