# Generated by Django 5.2 on 2025-06-22 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artworkcomment_artworklike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkcomment',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='artworks.artwork'),
        ),
        migrations.AlterField(
            model_name='artworklike',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artworks.artwork'),
        ),
        migrations.AlterUniqueTogether(
            name='artworklike',
            unique_together={('user', 'artwork')},
        ),
    ]
