# Generated by Django 5.2 on 2025-06-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_category_artwork_custom_size_artwork_frame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/extra/')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='artworks.artwork')),
            ],
        ),
    ]
