# Generated by Django 5.2 on 2025-06-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_alter_artworkcomment_artwork_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artworklike',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='artworkcomment',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork'),
        ),
        migrations.AlterField(
            model_name='artworklike',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork'),
        ),
    ]
