# Generated by Django 5.2 on 2025-06-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_artworkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
    ]
