# Generated by Django 5.2 on 2025-06-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_alter_artworklike_unique_together_and_more'),
        ('artworks', '0006_remove_artwork_category'),
    ]

    operations = [
    ]
