# Generated by Django 5.1.6 on 2025-06-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_merge_20250622_1644'),
        ('artworks', '0007_merge_20250622_1702'),
    ]

    operations = [
    ]
