# Generated by Django 5.1.7 on 2025-06-22 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_merge_20250622_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='categories',
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artworks.category'),
            preserve_default=False,
        ),
    ]
