# Generated by Django 5.1.7 on 2025-06-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_remove_artwork_categories_artwork_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
