# Generated by Django 5.1.6 on 2025-06-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_commentlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
