# Generated by Django 5.1.7 on 2025-05-31 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_address_order_delivery_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
