# Generated by Django 5.1.6 on 2025-06-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_user_alter_cartitem_artwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frame',
            field=models.CharField(blank=True, choices=[('none', 'No Frame'), ('wood', 'Wood Frame'), ('metal', 'Metal Frame'), ('acrylic', 'Acrylic Frame')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
