# Generated by Django 5.2 on 2025-06-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
